name: Generate Snake Animation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          snake_key: ${{ secrets.SNAKE_KEY || 'default' }}


